// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUbVaVM1o9wrnqklT-Ym3jF2YS9ogEEh0',
    appId: '1:261121895067:web:6f3fae40146c03437c343e',
    messagingSenderId: '261121895067',
    projectId: 'kiki-f290c',
    authDomain: 'kiki-f290c.firebaseapp.com',
    storageBucket: 'kiki-f290c.appspot.com',
    measurementId: 'G-RFV153WBFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFEBnLXg4mszX6XbAqhAW8_KZSAdp85RM',
    appId: '1:261121895067:android:38c2d543fd7ef3b57c343e',
    messagingSenderId: '261121895067',
    projectId: 'kiki-f290c',
    storageBucket: 'kiki-f290c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLoAYr1-KFnmVoxvpkbNmetXY3dQltU4',
    appId: '1:261121895067:ios:ab0546a4214f834d7c343e',
    messagingSenderId: '261121895067',
    projectId: 'kiki-f290c',
    storageBucket: 'kiki-f290c.appspot.com',
    iosBundleId: 'com.example.kiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxLoAYr1-KFnmVoxvpkbNmetXY3dQltU4',
    appId: '1:261121895067:ios:ab0546a4214f834d7c343e',
    messagingSenderId: '261121895067',
    projectId: 'kiki-f290c',
    storageBucket: 'kiki-f290c.appspot.com',
    iosBundleId: 'com.example.kiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUbVaVM1o9wrnqklT-Ym3jF2YS9ogEEh0',
    appId: '1:261121895067:web:bb38047a2fc5cdeb7c343e',
    messagingSenderId: '261121895067',
    projectId: 'kiki-f290c',
    authDomain: 'kiki-f290c.firebaseapp.com',
    storageBucket: 'kiki-f290c.appspot.com',
    measurementId: 'G-ZD9C8XZB98',
  );

}